#+TITLE: 配置支持中文输入的emacsclient
#+DATE: 2016-09-24
#+SETUPFILE: ~/Hexo/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: emacs
#+JEKYLL_TAGS: emacs
#+JEKYLL_PUBLISHED: true

因为习惯了 emacs 的高效编辑，所以一直想要将arch的默认编辑器设置为emacs。
然而 emacs 每次启动都要加载大量的配置文件，缓慢的打开速度使它很难作为快速的编辑工具来使用。

最近发现了一个非常不错的通过使用emacsclient来快速启动新的emacs窗口的解决方案。
并且通过一些额外的设置可以很好地支持中文输入。

* emacsclient
emacsclient 的原理十分简单，就是预先启动一个emacs作为守护进程，每次想要进行一个新的编辑时，就打开一个窗口并链接到守护进程。
这样就免去了最耗时的每次启动时的加载配置，十分快速的同时还拥有你自定义的配置。

对于emacs英文用户来说，在终端下直接运行如下命令即可打开终端下的或者带有图形界面的 emacs 客户端。

#+BEGIN_SRC bash
$ emacsclient -t -a ""  #在终端中开启emacs
$ emacsclient -nc -a ""  #启动emacs图形界面
#+END_SRC
其中-a ""参数表示，当第一次运行这个命令时，它会把emacs当作守护进程来启动，之后就会一直驻留在后台。
等到再次使用 emacsclient 时，就会把新建的窗口链接到该守护程序实现快速启动。

但是对于中文用户来说，进入后就会发现会遇到中文乱码，fcitx 输入法无法被激活的问题。
不过可以通过下面这些额外的设置来解决这两个问题。

* 新窗口中支持中文字体
因为在 emacs 中关于界面和字体的设置只有在创建新的frame时才有效，而启动服务器的时候并没有创建frame。
所以要想在 emacsclient 中正确的显示中文字体必须要添加一些额外的设置。

#+BEGIN_SRC emacs
(setq window-system-default-frame-alist
      '(
        ;; if frame created on x display
        (x
         (menu-bar-lines . 1)
         (tool-bar-lines . nil)
         ;; mouse
         (mouse-wheel-mode . 1)
         (mouse-wheel-follow-mouse . t)
         (mouse-avoidance-mode . 'exile)
         ;; face 具体可以更换为系统支持的中文字体
         (font . "WenQuanYi Micro Hei Mono 12")
         )
        ;; if on term
        (nil
         (menu-bar-lines . 0) (tool-bar-lines . 0)
         ;; (background-color . "black")
         ;; (foreground-color . "white")
         )
        )
      )
#+END_SRC

对于 spacemacs 用户来说，默认的配置已经解决了新窗口的字体问题，所以不需要再进行额外的设置了。

* 用户环境变量配置
一般言系统环境中LC_CTYPE默认设置为英文，此时在Emacs上可能无法使用输入法。为了能够支持fcitx的输入，在启动Emacs时需要指定LC_CTYPE为zh_CN.UTF-8。
使用下面的命令进行，就可以使用支持fcitx中文输入的emacs:

#+BEGIN_SRC bash
$ LC_CTYPE=zh_CN.UTF-8 emacs
#+END_SRC

当然你还可以利用alias别名命令来简化命令的输入。
比如我就在自己的个人环境信息配置文件(.profile或者.bashrc)中加入如下信息。

#+BEGIN_SRC bash
alias emacs='LC_CTYPE=zh_CN.UTF-8 emacs'
alias em='emacsclient -t -a ""'  #在终端中开启emacs
alias emc='LC_CTYPE=zh_CN.UTF-8 emacsclient -nc -a ""'  #启动emacs图形界面
export EDITOR="$(if [[ -n $DISPLAY ]]; then echo 'LC_CTYPE=zh_CN.UTF-8 emacsclient -a ""'; else echo 'vi'; fi)"
#+END_SRC

之后直接在终端下输入emc，就可以快速启动emacsclient的图形界面进行编辑了，就是这么简单哈。
* 参考
1.[[https://wiki.archlinux.org/index.php/Emacs_(%25E7%25AE%2580%25E4%25BD%2593%25E4%25B8%25AD%25E6%2596%2587)][Emacs--archwiki]]

2.[[http://emacser.com/daemon.htm][使用emacs daemon]]

3.[[https://wiki.archlinux.org/index.php/Fcitx_(%25E7%25AE%2580%25E4%25BD%2593%25E4%25B8%25AD%25E6%2596%2587)#Emacs_.E6.97.A0.E6.B3.95.E4.BD.BF.E7.94.A8.E8.BE.93.E5.85.A5.E6.B3.95][fcitx--archlinux]]
